// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2) {
  return window['go']['main']['App']['AddItem'](arg1, arg2);
}

export function ListItems() {
  return window['go']['main']['App']['ListItems']();
}
